name: 'Cleanup workspace'
description: 'Cleanup working directory and docker'
branding:
  icon: delete
  color: red
inputs:
  cleanup_docker:
    description: 'Delete all docker containers and volumes?'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Delete all files in the current directory
      shell: bash
      run: |
        find . -mindepth 1 -delete
    - name: Delete all docker containers and volumes
      if: ${{ inputs.cleanup_docker }}
      shell: bash
      run: |
        docker rm -f $(docker ps -aq)
        docker system prune --volumes --force
